### ISSUE TITLE
How to delete by query (for instance to delete all)?

### ISSUE THREAD

**Issue by biot023** [benashford/rs-es#116]
Hi -- I'm struggling to see how to implement a delete all query (or some equivalent).
I thought maybe creating and sending a crafted `DeleteOperation` was the answer but I can't see any way in the code to add a query to the operation struct instance.
Sorry if I'm missing something really obvious -- could anyone advise me on how to achieve a delete by query? Or, failing that, the best way to delete all documents in an index? Oh, but `delete_index` is too destructive.
Currently I'm thinking that I might just send an HTTP request to the delete by query endpoint. I'll do that if needs be, but I'm hoping there's a better way.
Thanks for any and all help, and thanks also for the brilliant crate!
   Doug.

**Comment by benashford** [comment]
Hello,

The reference version of ElasticSearch that rs-es supports is 2.0, which didn't have an (official) Delete by Query operation (the 1.x implementation was deprecated and the modern replacement hadn't been invented at the time).  Which is why there's no implementation of it.  Although my documentation isn't particularly clear about that, so apologies for that.

The workaround recommended by Elastic for the 2.0 version was to do a [scan/scroll](https://github.com/benashford/rs-es#scan-and-scroll) operation to find document IDs, then do a [bulk delete](https://github.com/benashford/rs-es#bulk) on those IDs.

In due-course the baseline ES version should be moved up as 2.0 is quite old now, but this is still in the future due to time-constraints elsewhere.

Thanks

**Comment by biot023** [comment]
Ah, thanks for that @benashford .
I completely understand about time constraints -- maybe one day I'll be proficient enough with Rust to be of use! :)
The only thing I really want the delete all for is for testing so I might still just go with an HTTP call -- whatever looks easiest, I reckon.
And I really appreciate both the response and the package generally -- thanks again!
   Doug.
