### ISSUE TITLE
Raw query support

### ISSUE THREAD

**Issue by stephanbuys** [benashford/rs-es#71]
Hi, do you think it would be feasible (or within the design of your project) to allow a user to specify the raw, json Query DSL string? Sometimes I use Kibana/Sense to prototype queries and just brining it across would be something similar to the ES Javascript client.

**Comment by KodrAus** [comment]
This is the exact reason I wrote [elastic_hyper](https://crates.io/crates/elastic_hyper) which is an option if @benashford wants to keep rs-es strongly typed

**Comment by stephanbuys** [comment]
@KodrAus awesome - thanks for the pointer

**Comment by benashford** [comment]
As @KodrAus says `elastic_hyper` is probably a more natural fit for that kind of use-case (I'll add a link to the README before I forget to).  I have thought about having some kind of general purpose "anything that's serializable" case to allow for customisations, but the problem is that loses information that is needed for certain features (e.g. aggregations are context sensitive, you need to know what the request was to deserialise the response correctly).
