### ISSUE TITLE
Question: Getting errors for basic API usage

### ISSUE THREAD

**Issue by maaronking** [benashford/rs-es#94]
I apologize if this is not the correct place to ask this question.  I know issues are normally related directly to problems in the software and this is more of a user problem.

When just trying to build the simple code below, I am getting the following error:

``` rust
// crates
extern crate rs_es;

// namespaces
use rs_es::Client;

fn main() {
    let mut client = match Client::new("http://localhost:9200") {
        Ok(c) => c,
        Err(_) => panic!("oops")
    };
    
    let index_op = client.index("RUST", "entry");
}
```

```
$ cargo build
   Compiling es-test v0.1.0 (file:///home/making/Develop/rust/es-test)
error[E0282]: unable to infer enough type information about `_`
  --> src/main.rs:14:27
   |
14 |     let index_op = client.index("RUST", "entry");
   |                           ^^^^^ cannot infer type for `_`
   |
   = note: type annotations or generic parameter binding required

error: aborting due to previous error

```

Thanks for any help you are able to provide.

**Comment by benashford** [comment]
This is because `client.index` returns an `IndexOperation` which has a generic parameter, and there's not enough information here for the Rust compiler to know what that parameter is.  The easiest way to tell it, is to provide the document to be indexed.  

For example: https://github.com/benashford/rs-es/blob/master/src/operations/index.rs#L161

The `with_doc` call tells the compiler what the generic parameter is and type inference does the rest.  Either that or you could define the type of `index_op` in-full before hand.
